---
title: ForDOOM MVP-0
---
flowchart TD
  style User fill:#7fd
  style Authentication fill:#7fd
  style Account fill:#7fd
  style Karma fill:#7fd
  style TopicList fill:#7fd

  style Topic fill:#bbf

  Forum[Форум]

  Forum --> User[Пользователи]

  User --> Account[Аккаунт]
  User --> Authentication[Аутентификация]

  Authentication --> Register([Регистрация])
  Authentication --> Login([Вход в систему])
  Authentication -->  Logout([Выход из системы])

  Account --> ChangeUserData([Изменить данные])
  Account --> ChangePassword([Изменить пароль])

  Topic[Темы]

  CreateTopic([Создать тему])
  DeleteTopic([Удалить тему])
  EditTopic([Редактировать тему])
  CloseTopic([Закрыть тему])

  Topic --> CreateTopic
  Topic --> DeleteTopic
  Topic --> EditTopic
  Topic --> CloseTopic

  Message[Сообщения]

  Message1([Отправить сообщение под темой])
  Message2([Удалить сообщение под темой])

  Message --> Message1
  Message --> Message2

  Topic --> Message

  Forum --> Topic

  Reaction[Реакции]

  AddReaction([Добавить реакцию])
  RemoveReaction([Удалить реакцию])

  Reaction --> AddReaction
  Reaction --> RemoveReaction

  Message --> Reaction

  TopicList[Лента тем]

  Topic --> TopicList 
  TopicList --> Search
 

  Search[Поиск по форуму]

  FindByUser([По автору])
  FindByTopic([По теме])

  Search --> FindByUser
  Search --> FindByTopic

  Filter[Фильтрация]

  FilterByName([По имени])
  FilterByDate([По новизне])
  FilterByPopularity([По популярности])

  Filter --> FilterByName
  Filter --> FilterByDate
  Filter --> FilterByPopularity

  TopicList --> Filter
  Search --> Filter

  Karma[Система кармы]

  User --> Karma

  Like([Прибавить рейтинг])
  Dislike([Отнять рейтинг])
  Sync([Синхронизация баллов])

  Karma --> Like
  Karma --> Dislike
  Karma --> Sync

  





